Repository OsamZo/hi-hello-spring, pull requests merged in 2024-11, with the labels that each got.

#4 [FEAT] 프로젝트 확인용 테스트 로직 구현 작업
  src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java
  src/main/java/spring/hi_hello_spring/test/command/application/dto/TestCreateReqDTO.java
  src/main/java/spring/hi_hello_spring/test/command/application/dto/TestUpdateReqDTO.java
  src/main/java/spring/hi_hello_spring/test/command/application/service/TestService.java
  src/main/java/spring/hi_hello_spring/test/command/domain/aggregate/entity/Test.java
  src/main/java/spring/hi_hello_spring/test/command/domain/repository/TestRepository.java
  src/main/java/spring/hi_hello_spring/test/command/infrastructure/repository/JpaTestRepository.java
  src/main/java/spring/hi_hello_spring/test/query/controller/TestQueryController.java
  src/main/java/spring/hi_hello_spring/test/query/dto/TestAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/test/query/dto/TestQueryDTO.java
  src/main/java/spring/hi_hello_spring/test/query/mapper/TestMapper.java
  src/main/java/spring/hi_hello_spring/test/query/service/TestQueryService.java
  src/main/resources/mapper/test/TestMapper.xml
Labels: FIX, FEAT, REFACTOR

#6 [REFACTOR] actions 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#10 [TEST] 깃허브 ac tions 테스트용 코드 변경
  src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java
Labels: TEST

#12 [FEAT] actions 코드 수정
  .github/workflows/deploy.yml
Labels: TEST

#14 [REFACTOR] Github Actions 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#16 [REFACTOR] Github Actions 설정 변경 작업
  .github/workflows/deploy.yml
Labels: REFACTOR

#18 [REFACTOR] 깃허브 액션 테스트
  .github/workflows/deploy.yml
Labels: REFACTOR, TEST

#20 [TEST] 깃허브 액션 테스트
  .github/workflows/deploy.yml
Labels: REFACTOR

#22 [TEST] Github Actions 테스트 작업
  .github/workflows/deploy.yml
  src/main/java/spring/hi_hello_spring/common/s3/FileUploadDTO.java
Labels: TEST

#24 [CHORE] 테스트용 코드 작성
  src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java
Labels: CHORE

#26 [FEAT] Security 기본 설정 작업
  build.gradle
  src/main/java/spring/hi_hello_spring/security/SecurityConfig.java
Labels: FEAT
