Repository OsamZo/hi-hello-spring, pull requests merged in 2024-12, with the labels that each got.

#29 [FEAT] DDL 생성
  src/main/resources/hihellodb.sql
Labels: FEAT

#31 [REFACTOR] ddl-auto none으로 변경
  src/main/resources/application.yml
Labels: REFACTOR

#34 [REFACTOR] DDL 리팩토링
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#36 [FEAT] data sql 데이터 추가 작업
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: FEAT

#39 [REFACTOR] DDL 수정
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#41 [REFACTOR] github actions 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#37 [FEAT] Entity 설계
  src/main/java/spring/hi_hello_spring/chatbot/command/domain/aggregate/entity/Chatbot.java
  src/main/java/spring/hi_hello_spring/chatbot/command/domain/aggregate/entity/ChatbotCategory.java
  src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Department.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Position.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalInd.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalList.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskEval.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskSubmit.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskType.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/aggregate/entity/finalEval.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/aggregate/entity/finalEvalInd.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/GroupMember.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReview.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReviewList.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Planning.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/PlanningStatus.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Report.java
  src/main/java/spring/hi_hello_spring/noti/command/domain/aggregate/entity/Noti.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/CheckListStatus.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Checklist.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/OnboardingStatus.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Template.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/TemplateType.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/Quiz.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/QuizCategory.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/QuizResult.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiModContent.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiSnapshot.java
Labels: FEAT

#42 [FEAT] 사원 로그인 기능 구현
  build.gradle
  src/main/java/spring/hi_hello_spring/common/util/CustomUserUtils.java
  src/main/java/spring/hi_hello_spring/config/BeanConfig.java
  src/main/java/spring/hi_hello_spring/config/SwaggerConfig.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/spring/hi_hello_spring/security/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/dto/LoginRequest.java
  src/main/java/spring/hi_hello_spring/security/filter/CustomAuthenticationFilter.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/JwtAccessDeniedHandler.java
  src/main/java/spring/hi_hello_spring/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginFailureHandler.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/util/CustomUserDetails.java
  src/main/java/spring/hi_hello_spring/security/util/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
  src/main/java/spring/hi_hello_spring/security/util/TokenService.java
  src/main/resources/application.yml
Labels: FEAT

#47 [FEAT] 멘티 전체 조회
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#50 [CHORE] Employee Entity 필드 수정
  src/main/java/spring/hi_hello_spring/common/aggregate/entity/EmployeeRole.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/util/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: CHORE

#53 [REFACTOR] DDL 구문 변경 작업
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#55 [CHORE] secretkey 수정 및 토큰 만료 시간 수정
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
  src/main/resources/application.yml
Labels: CHORE

#57 [FEAT] 동료 평가 지표 등록 기능 구현
  src/main/java/spring/hi_hello_spring/group/command/application/controller/PeerReviewListController.java
  src/main/java/spring/hi_hello_spring/group/command/application/dto/PeerReviewListCreateDTO.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/PeerReviewListService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReviewList.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/PeerReviewListRepository.java
  src/main/java/spring/hi_hello_spring/group/command/infrastructure/repository/JpaPeerReviewListRepository.java
Labels: FEAT, REFACTOR

#61 [FEAT] 부서별 멘티 조회 기능
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeDepQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#62 [FEAT] 동료 평가 지표 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/group/command/application/controller/PeerReviewListController.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/PeerReviewListService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/PeerReviewListRepository.java
Labels: FEAT

#64 멘토 전체 조회
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/MentorAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT, REFACTOR

#65 [FEAT] 동료 평가 지표 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewListQueryController.java
  src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewListAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewListMapper.java
  src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewListQueryService.java
  src/main/resources/data.sql
  src/main/resources/mapper/group/PeerReviewListMapper.xml
Labels: FEAT, REFACTOR

#69 [REFACTOR] ddl 구문 data 구문 변경 작업
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#70 [CHORE] SecurityRepository, EmployeeRepository 분리
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/spring/hi_hello_spring/security/repository/SecurityRepository.java
  src/main/java/spring/hi_hello_spring/security/util/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: CHORE

#73 [FEAT] 평가 지표 등록 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalIndController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalIndCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalIndService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalInd.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaEvalIndRepository.java
Labels: FEAT, REFACTOR

#72 [REFACTOR] DDL 수정
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#75 [REFACTOR] Actions 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#77 [FEAT] 평가 지표 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalIndController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalIndService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
Labels: FEAT

#81 [REFACTOR] Actions 코드 변경
  .github/workflows/deploy.yml
Labels: REFACTOR

#79 [FEAT] 평가 지표 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/EvalIndQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/EvalIndAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/EvalIndMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/EvalIndQueryService.java
  src/main/resources/mapper/evaluation/evalind/EvalIndMapper.xml
Labels: FEAT

#83 [FEAT] 퀴즈 카테고리 등록 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizCategoryCreateDTO.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizCategoryService.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/QuizCategory.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java
  src/main/java/spring/hi_hello_spring/quiz/command/infrastructure/repository/JpaQuizCategoryRepository.java
Labels: FEAT, REFACTOR

#85 [FEAT] 퀴즈 카테고리 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizCategoryService.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java
Labels: FEAT

#89 [FEAT] 카테고리 별 퀴즈 추가 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizCreateDTO.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/Quiz.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java
  src/main/java/spring/hi_hello_spring/quiz/command/infrastructure/repository/JpaQuizRepository.java
  src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizCategoryQueryController.java
Labels: FEAT, REFACTOR

#91 [FEAT] 카테고리 별 퀴즈 수정 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizUpdateDTO.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java
Labels: FEAT

#93 [FEAT] 카테고리 별 퀴즈 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java
  src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java
Labels: FEAT

#96 [FEAT] 멘티 그룹핑 구현
  src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java
  src/main/java/spring/hi_hello_spring/group/command/application/dto/MemberDTO.java
  src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestDTO.java
  src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestWrapper.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/GroupMember.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/GroupMemberRepository.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java
Labels: FEAT

#97 [FEAT] 위키 등록 기능 구현
  src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/dto/WikiCreateRequestDTO.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiModContent.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiSnapshot.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiModContentRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiSnapshotRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiModContentRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiSnapshotRepository.java
Labels: FEAT

#101 [FEAT] 멘토-멘티 그룹핑 구현
  src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringMatchController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/MentoringGroupDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
Labels: FEAT, REFACTOR

#102 [FEAT] 카테고리 별 퀴즈 전체 조회 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizQueryController.java
  src/main/java/spring/hi_hello_spring/quiz/query/dto/QuizAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/quiz/query/mapper/QuizMapper.java
  src/main/java/spring/hi_hello_spring/quiz/query/service/QuizQueryService.java
  src/main/resources/mapper/quiz/QuizMapper.xml
Labels: FEAT

#104 [FEAT] 로그인 시 발급 된 리프레시 토큰을 Redis에 저장하도록 구현
  src/main/java/spring/hi_hello_spring/common/util/CustomUserUtils.java
  src/main/java/spring/hi_hello_spring/common/util/RedisService.java
  src/main/java/spring/hi_hello_spring/config/RedisConfig.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/entity/CustomUserDetails.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/repository/SecurityRepository.java
  src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/service/TestTokenService.java
  src/main/java/spring/hi_hello_spring/security/service/TokenService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
  src/main/java/spring/hi_hello_spring/security/util/TokenService.java
  src/main/resources/application.yml
Labels: FEAT, CHORE

#106 [FEAT] 위키 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/wiki/query/controller/WikiQueryController.java
  src/main/java/spring/hi_hello_spring/wiki/query/dto/WikiListQueryDTO.java
  src/main/java/spring/hi_hello_spring/wiki/query/mapper/WikiMapper.java
  src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java
  src/main/resources/mapper/wiki/WikiMapper.xml
Labels: FEAT

#109 [REFACTOR] ddl, data 구문 변경 작업
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#111 [REFACTOR] Github Actions 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#112 [FEAT] 검증 과정 보완 및 리프레시 토큰 관리 추가
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/service/TestTokenService.java
  src/main/java/spring/hi_hello_spring/security/service/TokenService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
  src/main/resources/data.sql
Labels: FEAT, CHORE

#114 [FEAT] 과제 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskHrAllListQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/data.sql
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#116 [FEAT] 로그아웃 기능 구현
  src/main/java/spring/hi_hello_spring/common/util/RedisService.java
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FEAT, CHORE

#117 [FEAT] (멘토) 과제 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskAllListQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#126 [FIX] 순환 의존성 오류 해결
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FIX

#128 [FIX] 요청 시 JwtFilter에서 걸리는 문제 해결
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FIX

#129 [FEAT] 위키 수정 기능 구현
  src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/dto/WikiUpdateRequestDTO.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiModContent.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiSnapshot.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiModContentRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiRepository.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiSnapshotRepository.java
Labels: FEAT

#130 [FEAT] 온보딩 스토리 보드 등록 기능 구현
  src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java
  src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TemplateCreateDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Template.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
  src/main/java/spring/hi_hello_spring/onboarding/command/infrastructure/repository/JpaTemplateRepository.java
Labels: FEAT

#135 [FEAT] 온보딩 스토리 보드 순서 수정 기능 구현
  src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java
  src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TeamplateOrderUpdateDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
Labels: FEAT

#137 [FEAT] 온보딩 스토리보드 순서 전체 조회 기능 구현
  src/main/java/spring/hi_hello_spring/onboarding/query/controller/TemplateQueryController.java
  src/main/java/spring/hi_hello_spring/onboarding/query/dto/TemplateAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/TemplateMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/TemplateQueryService.java
  src/main/resources/mapper/onboarding/TemplateMapper.xml
Labels: FEAT

#139 [FEAT] 카테고리 별 퀴즈 결과 전체 조회 기능 구현
  src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizResultQueryController.java
  src/main/java/spring/hi_hello_spring/quiz/query/dto/QuizResultAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/quiz/query/mapper/QuizResultMapper.java
  src/main/java/spring/hi_hello_spring/quiz/query/service/QuizResultQueryService.java
  src/main/resources/data.sql
  src/main/resources/mapper/quiz/QuizResultMapper.xml
Labels: FEAT

#119 [FEAT] (멘토) 과제 상세조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#144 [FEAT] 위키 히스토리 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/wiki/query/controller/WikiQueryController.java
  src/main/java/spring/hi_hello_spring/wiki/query/dto/WikiHistoryListQueryDTO.java
  src/main/java/spring/hi_hello_spring/wiki/query/mapper/WikiMapper.java
  src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java
  src/main/resources/mapper/wiki/WikiMapper.xml
Labels: FEAT

#145 [FEAT] 위키 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java
  src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiRepository.java
Labels: FEAT

#142 [FEAT] 그룹 과제 제목 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/GroupTaskAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#149 [FEAT] 그룹 과제 별 그룹 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/group/query/controller/TaskGroupQueryController.java
  src/main/java/spring/hi_hello_spring/group/query/dto/TaskGroupListQueryDTO.java
  src/main/java/spring/hi_hello_spring/group/query/mapper/TaskGroupMapper.java
  src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java
  src/main/resources/mapper/group/TaskGroupMapper.xml
Labels: FEAT

#153 [REFACTOR] github actions 코드 변경
  .github/workflows/deploy.yml
Labels: REFACTOR

#158 [FEAT] 동료 평가 결과 리스트 조회
  src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewResultQueryController.java
  src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewResultAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewResultMapper.java
  src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewResultQueryService.java
  src/main/resources/mapper/group/PeerReviewResultMapper.xml
Labels: FEAT

#155 [FEAT] 과제 평가 항목 등록 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalListController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalListCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalListService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalList.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaEvalListRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaTaskRepository.java
Labels: FEAT

#161 [FEAT] (담당자) 사원 등록 기능 구현
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/dto/HR/CreateEmplReqDTO.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Department.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Position.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/DepartmentRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/PositionRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaDepartmentRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaEmployeeRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaPositionRepository.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FIX, FEAT, CHORE

#163 [FEAT] 사원 비밀번호 변경 기능 구현
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/dto/employee/ModifyPasswordReqDTO.java
  src/main/java/spring/hi_hello_spring/employee/command/application/dto/hr/CreateEmplReqDTO.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FEAT, CHORE

#165 [FEAT] 사원 수정 기능 구현
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/dto/hr/ModifyEmplReqDTO.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
Labels: FEAT

#168 [FEAT] 사원 삭제 기능 구현
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
Labels: FEAT

#143 [FEAT] 과제 등록 기능 구현
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalListCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalList.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/service/EvalListDomainService.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Template.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/service/TemplateDomainService.java
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: FEAT

#169 [FEAT] 과제 평가 등록 기능 구현
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskEvalController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskEvalCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskEvalService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskEval.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskEvalRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskSubmitRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaTaskEvalRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaTaskSubmitRepository.java
  src/main/resources/data.sql
Labels: FEAT, CHORE

#171 [FEAT] 채팅 구현, STOM, mongoDB
  build.gradle
  docker-compose.yml
  src/main/java/spring/hi_hello_spring/HiHelloSpringApplication.java
  src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java
  src/main/java/spring/hi_hello_spring/chatting/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/controller/ChatRoomController.java
  src/main/java/spring/hi_hello_spring/chatting/domain/aggregate/ChatMessage.java
  src/main/java/spring/hi_hello_spring/chatting/domain/repository/mongo/ChatMessageMongoRepository.java
  src/main/java/spring/hi_hello_spring/chatting/dto/ChatRequestMessage.java
  src/main/java/spring/hi_hello_spring/chatting/dto/ChatRoom.java
  src/main/java/spring/hi_hello_spring/chatting/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/config/MongoConfig.java
  src/main/java/spring/hi_hello_spring/config/SocketTextHandler.java
  src/main/java/spring/hi_hello_spring/config/StringToZonedDateTimeConverter.java
  src/main/java/spring/hi_hello_spring/config/ZonedDateTimeToStringConverter.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
  src/main/resources/application.yml
  src/main/resources/static/chat.html
Labels: FEAT, REFACTOR

#173 [REFACTOR] DDL 및 더미 데이터 수정
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#174 [FEAT] 최종 평가 등록 기능 구현
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskEvalRepository.java
  src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaEvalListRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/controller/FinalEvalController.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/dto/FinalEvalCreateDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/service/FinalEvalService.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/aggregate/entity/FinalEval.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/aggregate/entity/FinalEvalInd.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/repository/FinalEvalIndRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/repository/FinalEvalRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/infrastructure/JpaFinalEvalIndRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/infrastructure/JpaFinalEvalRepository.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReviewList.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/GroupMemberRepository.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/PeerReviewRepository.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java
  src/main/java/spring/hi_hello_spring/group/command/infrastructure/repository/JpaGroupMemberRepository.java
  src/main/java/spring/hi_hello_spring/group/command/infrastructure/repository/JpaPeerReviewRepository.java
  src/main/java/spring/hi_hello_spring/group/command/infrastructure/repository/JpaTaskGroupRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Report.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/ReportRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/infrastructure/repository/JpaMentoringRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/infrastructure/repository/JpaReportRepository.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
  src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizResultRepository.java
  src/main/java/spring/hi_hello_spring/quiz/command/infrastructure/repository/JpaQuizResultRepository.java
Labels: FEAT, CHORE

#184 [FEAT] (멘티) 보고서 내용 작성 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/WriteReportDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Report.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/ReportRepository.java
Labels: FEAT

#185 [FEAT] 최종평가 목록 조회 기능 구현
  src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java
  src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalsQueryDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java
  src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java
  src/main/resources/mapper/finalEval/FinalEvalMapper.xml
Labels: FEAT

#187 [FEAT] (멘티) 보고서 내용 수정 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/ReportRepository.java
Labels: FEAT

#189 [FEAT] 멘토링 계획서 등록
  src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java
  src/main/java/spring/hi_hello_spring/common/repository/FileRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/MentoringPlanRequestDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Planning.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/PlanningRepository.java
  src/main/resources/hihellodb.sql
Labels: FEAT, REFACTOR

#190 [FEAT] 동료 평가 결과 상세 조회 기능 구현
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReview.java
  src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewResultQueryController.java
  src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewResultDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewResultMapper.java
  src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewResultQueryService.java
  src/main/resources/application.yml
  src/main/resources/mapper/group/PeerReviewResultMapper.xml
Labels: FEAT, REFACTOR

#191 [FEAT] (멘토) 보고서 피드백 작성/수정 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/WriteFeedbackDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java
Labels: FEAT, CHORE

#192 [FEAT] 멘토링 계획서 삭제
  src/main/java/spring/hi_hello_spring/common/repository/FileRepository.java
  src/main/java/spring/hi_hello_spring/common/s3/FileUploadUtil.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java
Labels: FEAT, REFACTOR

#193 [FEAT] 멘토링 계획서 처리
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/MentoringPlanUpdateDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java
Labels: FEAT

#194 [FEAT] 최종평가 상세조회 기능 구현
  src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java
  src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java
  src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java
  src/main/resources/mapper/finalEval/FinalEvalMapper.xml
Labels: FEAT

#196 [REFACTOR] DDL 수정
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#197 [FEAT] 멘토링 계획서 전체 리스트 조회
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanListAllQueryDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java
  src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
Labels: FEAT

#198 [FEAT] 멘토링 계획서 상세 조회
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanDetailDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java
  src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
Labels: FEAT

#200 [FEAT] 사원 내 프로필 조회 기능 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT, CHORE

#202 [CHORE] service 계층 Transactional 추가
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java
Labels: CHORE

#205 [CHORE] 멘토링 테이블에 멘토링 진행 현황 컬럼 추가
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: CHORE

#204 [FEAT] 멘토링 계획서 검색(name, title)
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanSearchDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java
  src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
Labels: FEAT

#207 [REFACTOR] DDL 수정에 따른 리팩토링
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
  src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java
Labels: REFACTOR

#208 [FEAT] 과제 평가 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalListQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java
  src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
Labels: FEAT

#210 [FEAT] (멘티) 멘토 프로필 조회 기능 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
Labels: FEAT

#212 [CHORE] 멘토/멘티 프로필 조회 기능 통합 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
Labels: CHORE

#214 [FIX] 그룹 과제 평가 리스트 조회 문제 해결
  src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
Labels: FIX

#215 [FEAT] 과제 평가 상세조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalDetailsQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java
  src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
Labels: FEAT

#218 [REFACTOR] DDL 수정
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#219 [CHORE] 프로필 조회 프로필 사진까지 조회되도록 수정
  src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: CHORE

#222 [REFACTOR] DDL 수정
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#224 [REFACTOR] DDL 수정
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#226 [REFACTOR] data.sql 수정
  src/main/resources/data.sql
Labels: REFACTOR

#227 [FEAT] 멘토링 보고서 상세 조회 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/ResMentoringReportDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java
  src/main/resources/data.sql
  src/main/resources/mapper/mentoring/ReportMapper.xml
Labels: FEAT

#233 [FEAT] data sql 데이터 추가 (퀴즈)
  src/main/resources/data.sql
Labels: FEAT

#234 [FEAT] (담당자) 멘토링 보고서 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/ReportListQueryDTO.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java
  src/main/resources/mapper/mentoring/ReportMapper.xml
Labels: FEAT, CHORE

#235 [FEAT] (팀장) 멘토링 보고서 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java
  src/main/resources/data.sql
  src/main/resources/mapper/mentoring/ReportMapper.xml
Labels: FEAT, CHORE

#236 [FEAT] (멘토) 멘토링 보고서 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java
  src/main/resources/mapper/mentoring/ReportMapper.xml
Labels: FEAT

#239 [FEAT] 사원 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/EmployeeListDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#242 [CHORE] 프로필 조회 DTO 추가 및 쿼리문 수정
  src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: CHORE

#243 [FEAT] 멘토링 채팅방 조회
  src/main/java/spring/hi_hello_spring/HiHelloSpringApplication.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatRoomController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/repository/mongo/ChatMessageMongoRepository.java
  src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java
  src/main/java/spring/hi_hello_spring/chatting/query/dto/ChattingRoomList.java
  src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java
  src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java
  src/main/resources/mapper/chatting/ChattingListMapper.xml
Labels: FEAT

#247 [FEAT] 사원 검색 기능 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#249 [FEAT] 그룹핑 방 생성, 조회
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatRoomController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java
  src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java
  src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/GroupMemberRepository.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java
  src/main/resources/mapper/chatting/ChattingListMapper.xml
Labels: FEAT, REFACTOR

#250 [FEAT] (담당자, 팀장) 멘토링 보고서 검색 기능 구현
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java
  src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java
  src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java
  src/main/resources/mapper/mentoring/ReportMapper.xml
Labels: FEAT

#253 [FEAT] 채팅 내역 조회
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatRoomController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatResponseMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/repository/mongo/ChatMessageMongoRepository.java
  src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java
  src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java
Labels: FEAT

#254 [FEAT] 온보딩 리스트 조회 기능 구현
  src/main/java/spring/hi_hello_spring/onboarding/query/controller/OnboardingQueryController.java
  src/main/java/spring/hi_hello_spring/onboarding/query/dto/CompletedStatusDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/dto/OnboardingDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/dto/OnboardingResDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/OnboardingMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/OnboardingQueryService.java
  src/main/resources/mapper/onboarding/OnboardingMapper.xml
Labels: FEAT, CHORE

#257 [FEAT] 사원 이름 조회 기능 구현
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#259 [FEAT] CORS 설정 작업
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
Labels: FEAT

#260 [FEAT] kafka 적용
  docker-compose.yml
  src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java
  src/main/java/spring/hi_hello_spring/config/KafkaConfig.java
  src/main/java/spring/hi_hello_spring/config/ListenerConfiguration.java
  src/main/java/spring/hi_hello_spring/config/MongoConfig.java
  src/main/java/spring/hi_hello_spring/config/ProducerConfiguration.java
  src/main/resources/application.yml
Labels: FEAT

#262 [FIX] roomId 값 겹치는 오류
  src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/domain/repository/mongo/ChatMessageMongoRepository.java
  src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestDTO.java
Labels: FEAT, REFACTOR

#264 [REFACTOR] 위키 등록 로직 리팩토링
  build.gradle
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java
  src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java
Labels: FEAT, REFACTOR

#266 [FEAT] 과제 검색 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskInputSearchQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskSearchQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#268 [FEAT] 그룹과제 동료 조회 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskGroupPartnerQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskInputSearchQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: FEAT

#274 [REFACTOR] DDL 수정
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#277 [REFACTOR] Spring Security CORS 설정 및 엔드포인트 변경
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/filter/CustomAuthenticationFilter.java
Labels: REFACTOR

#278 [FEAT] 알림 전송 기능 구현
  src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java
  src/main/java/spring/hi_hello_spring/notify/controller/NotifyController.java
  src/main/java/spring/hi_hello_spring/notify/dto/NotifyDTO.java
  src/main/java/spring/hi_hello_spring/notify/entity/NotiType.java
  src/main/java/spring/hi_hello_spring/notify/entity/Notify.java
  src/main/java/spring/hi_hello_spring/notify/repository/EmitterRepository.java
  src/main/java/spring/hi_hello_spring/notify/repository/EmitterRepositoryImpl.java
  src/main/java/spring/hi_hello_spring/notify/repository/NotifyRepository.java
  src/main/java/spring/hi_hello_spring/notify/service/NotifyService.java
  src/main/java/spring/hi_hello_spring/notify/service/NotifyServiceImpl.java
Labels: FEAT

#283 [CHORE] 로그인 엔드포인트 및 필터 설정 변경
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
Labels: CHORE

#285 [FEAT] 과제제출 기능 구현
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskSubmit.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java
Labels: FEAT

#288 [CHORE] 과제 제출 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskSubmit.java
Labels: CHORE

#294 [REFACTOR] chatRoomId 컬럼 추가 및 코드 변경
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
  src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java
  src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java
  src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#292 [CHORE] 멘티 본인 과제 상세조회 기능 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: CHORE

#295 [REFACOTR] 멘토 멘티 과제 상세조회 기능 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMentorDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: CHORE

#297 [CHORE] 멘토 과제 리스트 조회 기능 쿼리문 수정
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: REFACTOR

#299 [CHORE] 담당자 과제 리스트 조회 기능 쿼리문 수정
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskAllListQueryDTO.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
Labels: REFACTOR

#302 [REFACTOR] type 수정
  src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java
  src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java
  src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java
  src/main/resources/mapper/chatting/ChattingListMapper.xml
Labels: REFACTOR

#306 [REFACTOR] WikiListQueryDTO 컬럼명 변경
  src/main/java/spring/hi_hello_spring/wiki/query/dto/WikiListQueryDTO.java
  src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java
  src/main/resources/mapper/wiki/WikiMapper.xml
Labels: REFACTOR

#307 [REFACTOR] 과제 등록 기능 코드 수정
  src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java
  src/main/resources/data.sql
  src/main/resources/hihellodb.sql
Labels: REFACTOR

#309 [REFACTOR] 과제 수정 기능 코드 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskUpdateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
Labels: REFACTOR

#311 [REFACTOR] 과제 제출 기능 코드 수정
  src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
Labels: REFACTOR

#313 [REFACTOR] mongoDB 저장
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
Labels: REFACTOR

#315 [FIX] 위키 조회 시 오류 해결
  src/main/resources/mapper/wiki/WikiMapper.xml
Labels: FIX

#317 [CHORE] 시큐리티 엑세스 토큰 생성 과정 수정
  src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: CHORE

#319 [FEAT] 최종 평가 목록 검색 기능 구현
  src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java
  src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java
  src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java
  src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
  src/main/resources/mapper/finalEval/FinalEvalMapper.xml
Labels: FEAT

#320 [REFACTOR] kafka topic 수정
  docker-compose.yml
  src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java
  src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java
  src/main/java/spring/hi_hello_spring/config/ListenerConfiguration.java
  src/main/java/spring/hi_hello_spring/config/SocketTextHandler.java
  src/main/resources/application.yml
Labels: REFACTOR

#322 [CHORE] 멘토/멘티 프로필 조회 api 분리
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: CHORE

#324 [CHORE] 멘토/멘티 온보딩 리스트 조회 api 분리
  src/main/java/spring/hi_hello_spring/onboarding/query/controller/OnboardingQueryController.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/OnboardingMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/OnboardingQueryService.java
  src/main/resources/mapper/onboarding/OnboardingMapper.xml
Labels: CHORE

#326 [CHORE] 로그인 시 리프레시 토큰 저장 활성화
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
Labels: CHORE

#328 [CHORE] 사원 관련 API 엔드포인트 수정
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
Labels: REFACTOR

#330 [FIX] 한국어 깨짐 오류
  src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java
Labels: FIX

#334 [CHORE] 과제 등록 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
Labels: CHORE

#336 [REFACTOR] 퀴즈 카테고리 등록 코드 리펙토링
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java
Labels: REFACTOR

#332 [CHORE] docker mongodb 버전 수정
  docker-compose.yml
Labels: CHORE

#340 [REFACTOR] @RequestBody 속성 추가 작업
  src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java
Labels: REFACTOR

#338 [FIX] 토큰 검증 과정 무한 루프 원인 수정
  src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java
  src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/DepartmentRepository.java
  src/main/java/spring/hi_hello_spring/employee/command/domain/repository/PositionRepository.java
  src/main/java/spring/hi_hello_spring/security/entity/CustomUserDetails.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
  src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: FIX

#346 [REFACTOR] planningSeq 추가
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanListAllQueryDTO.java
  src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
Labels: REFACTOR

#348 [REFACTOR] @RequestBody 추가
  src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java
Labels: REFACTOR

#352 [FEAT] 부서별 멘토 조회
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/DepartmentListDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/MentorDepQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: FEAT

#353 [REFACTOR] mentor, seq 변경
  src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeDepQueryDTO.java
  src/main/java/spring/hi_hello_spring/employee/query/dto/MentorDepQueryDTO.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: REFACTOR

#355 [REFACTOR] jwt 생성 시 한글값은 utf-8로 인코딩 해서 삽입
  src/main/java/spring/hi_hello_spring/security/entity/CustomUserDetails.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: REFACTOR

#357 [REFACTOR] 최종 평가 상세 조회 기능 리팩토링
  src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java
  src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalDetailQueryDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalResultQueryDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java
  src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java
  src/main/resources/mapper/finalEval/FinalEvalMapper.xml
Labels: REFACTOR
