Repository OsamZo/hi-hello-spring, pull requests merged in 2025-01, with the labels that each got.

#505 [REFACTOR] 멘토링 매칭 조회 수정
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: REFACTOR

#507 [REFACTOR] 채팅 관련 시큐리티
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
Labels: REFACTOR

#512 [REFACTOR] 과제 조회 시 데이터에 taskType도 전달
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalListQueryDTO.java
  src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
Labels: REFACTOR

#516 [CHORE] 쿼리문 수정
  src/main/resources/mapper/onboarding/TemplateMapper.xml
Labels: CHORE

#518 [FIX] 주차 조회 수정, data.sql 수정
  src/main/resources/data2.sql
  src/main/resources/mapper/onboarding/TemplateMapper.xml
Labels: FIX

#520 [REFACTOR] 매칭이 된 멘티, 전체 멘티 조회 분리
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: REFACTOR

#523 [REFACTOR] GenerateType AUTO -> IDENTITY
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/CheckListStatus.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/OnboardingStatus.java
Labels: REFACTOR

#526 [FIX] checklist service문 수정
  src/main/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListService.java
Labels: FIX

#529 [FIX] 체크리스트 모두 체크 시 온보딩 수행 상태 변경 오류 해결
  src/main/java/spring/hi_hello_spring/employee/query/dto/ResEmplInfoQueryDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/controller/ChecklistQueryController.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/ChecklistMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/ChecklistQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
  src/main/resources/mapper/onboarding/ChecklistMapper.xml
Labels: FIX

#531 [REFACTOR] 온보딩 과제 등록 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskCreateDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java
  src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java
  src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
Labels: REFACTOR

#532 [FIX] S3 로직 수정
  src/main/java/spring/hi_hello_spring/common/s3/FileUploadUtil.java
Labels: FIX

#534 [FIX] Task 기능 로직 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskSubmitQueryController.java
  src/main/java/spring/hi_hello_spring/evaluation/query/dto/SubmittedTaskQueryDTO.java
  src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskSubmitQueryMapper.java
  src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskSubmitQueryService.java
  src/main/java/spring/hi_hello_spring/mentoring/query/dto/MenteeQueryDTO.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/OnboardingMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/OnboardingQueryService.java
  src/main/resources/mapper/evaluation/taskSubmit/TaskSubmitMapper.xml
  src/main/resources/mapper/onboarding/OnboardingMapper.xml
Labels: FIX

#537 [FEAT] 읽지 않은 알림 개수 조회 기능 구현
  src/main/java/spring/hi_hello_spring/notify/query/controller/NotifyQueryController.java
  src/main/java/spring/hi_hello_spring/notify/query/dto/AlarmCountDTO.java
  src/main/java/spring/hi_hello_spring/notify/query/mapper/NotifyMapper.java
  src/main/java/spring/hi_hello_spring/notify/query/service/NotifyQueryService.java
  src/main/resources/mapper/notify/NotifyMapper.xml
Labels: FEAT

#539 [REFACTOR] 최종 평가 등록 코드 리팩토링
  src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/controller/FinalEvalController.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/dto/FinalEvalCreateDTO.java
  src/main/java/spring/hi_hello_spring/finalEval/command/application/service/FinalEvalService.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/aggregate/entity/FinalEval.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/repository/FinalEvalIndRepository.java
  src/main/java/spring/hi_hello_spring/finalEval/command/domain/repository/FinalEvalRepository.java
  src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java
  src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
Labels: REFACTOR

#540 [TEST] Task, Onboarding 기능 테스트 코드 작성
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskEvalServiceTest.java
  src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskServiceTest.java
  src/test/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryServiceTest.java
  src/test/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListServiceTest.java
Labels: TEST

#542 [REFACTOR] Security 리팩토링
  src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
  src/main/java/spring/hi_hello_spring/security/config/SecurityProperties.java
  src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
  src/main/java/spring/hi_hello_spring/security/handler/JwtAccessDeniedHandler.java
  src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: REFACTOR

#544 [REFACOTR] 엘라스틱 서치 활성화
  src/main/resources/application.yml
Labels: REFACTOR

#549 [REFACTOR] deploy 코드 수정
  .github/workflows/deploy.yml
Labels: REFACTOR

#550 [FIX] 엘라스틱 서치 수정
  src/main/java/spring/hi_hello_spring/config/ElasticsearchConfig.java
Labels: FIX

#552 [CHORE] 엘라스틱 서치 로그 코드 추가
  src/main/java/spring/hi_hello_spring/config/ElasticsearchIndexInitializer.java
  src/main/java/spring/hi_hello_spring/elasticsearch/command/controller/ElasticsearchController.java
  src/main/java/spring/hi_hello_spring/elasticsearch/query/service/ElasticsearchQueryService.java
Labels: CHORE

#553 [FIX] 과제 등록 기능 로직 수정
  src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
  src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java
  src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java
  src/main/java/spring/hi_hello_spring/onboarding/query/controller/TemplateQueryController.java
  src/main/java/spring/hi_hello_spring/onboarding/query/mapper/TemplateMapper.java
  src/main/java/spring/hi_hello_spring/onboarding/query/service/TemplateQueryService.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
  src/main/resources/mapper/onboarding/TemplateMapper.xml
  src/test/java/spring/hi_hello_spring/HiHelloSpringApplicationTests.java
Labels: FIX

#555 [CHORE] 엑세스 토큰 만료시간 설정
  src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Labels: CHORE

#557 [FIX] 과제 등록, 조회 버그 수정
  src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
  src/main/resources/mapper/evaluation/task/TaskMapper.xml
  src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskServiceTest.java
Labels: FIX

#558 [REFACTOR] 과제 그룹 매핑 수정
  src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeAllQueryDTO.java
  src/main/resources/mapper/employee/EmployeeMapper.xml
Labels: REFACTOR

#561 [REFACTOR] 배포 환경 테스트
  .github/workflows/deploy.yml
Labels: FEAT

#564 [CHORE] 공백 추가
  .github/workflows/develop.yml
Labels: CHORE
